#!/bin/bash

# Check if Dredger is running on Eclipse Che
if [ -n "$CHE_PROJECTS_ROOT" ]
then
  if tty -s
  then
    fgRed=$(tput setaf 1)
    fgGreen=$(tput setaf 2)
    fgNormal=$(tput sgr0)
    fgBold=$(tput bold)
  fi

  hash jq 2>/dev/null || { echo -e >&2 "${fgRed}I require jq when running in Eclipse Che but it's not installed. Aborting!${fgNormal}"; exit 1; }

  DREDGER_CHE_MOUNT=$(docker inspect --format '{{ range .Mounts }}{{ if eq .Destination "'"$CHE_PROJECTS_ROOT"'" }}{{ .Source }}{{ end }}{{ end }}' $HOSTNAME 2>/dev/null) || {
      echo -e >&2 "${fgRed}Unable to determine Eclipse Che host mount point. Aborting!${fgNormal}"; 
      exit 1; 
  }

  DREDGER_CHE_INFO=$(curl -s $CHE_API/workspace/$CHE_WORKSPACE_ID?token=$CHE_MACHINE_TOKEN) || {
      echo -e >&2 "${fgRed}Unable to connect to Eclipse Che API. Aborting!${fgNormal}"; 
      exit 1; 
  }

  if [[ ${PWD} != *"$CHE_PROJECTS_ROOT"* ]]
  then
    cd $CHE_PROJECTS_ROOT/*/;
  fi

  DREDGER_CHE_PROJECT=$(echo ${PWD#$CHE_PROJECTS_ROOT} | cut -d '/' -f 2)
  if [ -z "$DREDGER_CHE_PROJECT" ]
  then
    DREDGER_CHE_PROJECT=$(echo $DREDGER_CHE_INFO | jq -re '.config .projects | first | .name | select (.!=null)') || {
        echo -e >&2 "${fgRed}Could not detect Eclipse Che project name. Aborting!${fgNormal}"; 
        exit 1; 
    }
  fi

  DREDGER_CHE_WORKSPACE=$(echo $DREDGER_CHE_INFO | jq -re '.config .name | select (.!=null)' || basename $DREDGER_MOUNT)
  DREDGER_CHE_HOST=$(echo $DREDGER_CHE_INFO | jq -re 'first(..|.dredgerHost? | select(.!=null))')

  # Set Dredger defaults
  export DREDGER_NAME=$DREDGER_CHE_PROJECT.$DREDGER_CHE_WORKSPACE${DREDGER_CHE_HOST:+.$DREDGER_CHE_HOST}
  export DREDGER_HOST=$DREDGER_CHE_PROJECT.$DREDGER_CHE_WORKSPACE.${DREDGER_CHE_HOST:-localhost}
  export DREDGER_MOUNT=$DREDGER_CHE_MOUNT/$DREDGER_CHE_PROJECT
  export DREDGER_PWD=$CHE_PROJECTS_ROOT/$DREDGER_CHE_PROJECT
  export DREDGER_NETWORK=${CHE_WORKSPACE_ID}_default

  echo -e "Detected Eclipse Che project ${fgBold}$DREDGER_CHE_WORKSPACE/$DREDGER_CHE_PROJECT${fgNormal} with host ${fgGreen}http://$DREDGER_HOST${fgNormal}"
fi

exec make --silent ${CHE_PROJECTS_ROOT:+"--include-dir=$CHE_PROJECTS_ROOT/$DREDGER_CHE_PROJECT"} -f /usr/local/dredger/Makefile ARGS="${*:2}" "$1"
